# Generated by Django 4.0.5 on 2022-06-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('courses', '0003_alter_courses_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='student',
            field=models.ManyToManyField(blank=True, to='student.student'),
        ),
    ]
